name: Publish on Docker

on: [push]

jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build a Docker image
        run: docker build -t moabora .

  deploy:
    name: Deploy
    needs: build
    runs-on: self-hosted
    steps:
      - name: Stop old container
        run: docker stop moabora-run || true
      - name: Prune old container
        run: docker rm moabora-run || true
      - name: Deploy new container
        run: docker run -dp 3000:3000 --name moabora-run moabora
